puts "Cleaning database..."

Hrservice.destroy_all
Meeting.destroy_all
User.destroy_all

puts "Creating Hrservices"

feedback_cv_lm = Hrservice.create!(title: "Feedback CV/lettre de motivation", description: "Le feedback que vous n’avez jamais eu sur votre CV et/ou votre lettre de motivation", conditions: ["Analyse de votre CV par un RH","Entretien de debriefing 45min (Skype ou face à face si vous êtes sur Paris)","Synthèse écrite"], price: 24.99, entry_service: true, hrsunit: true, hrsbundle: false, options: "(seront déduit du montant total si vous souhaitez continuer avec l’Update CV)")
feedback_linkedin = Hrservice.create!(title: "Feedback LinkedIn", description: "Le diagnostic RH et communication de votre visibilité sur internet", conditions: ["Analyse de votre empreinte digitale","Entretien de debriefing 45min (Skype ou face à face si vous êtes sur Paris)","Synthèse écrite"], price: 24.99, entry_service: true, hrsunit: true, hrsbundle: false, options: "(le prix sera déduit du montant total si vous souhaitez continuer avec l’Update LinkedIn)")
update_cv = Hrservice.create!(title: "Update CV", description: "Redonnez un coup de jeune à votre CV", conditions: ["Entretien initial de 45 min pour cibler votre besoin","Analyse de votre CV par un RH","Regard complémentaire d’un expert en communication","Entretien de restitution 45min (Skype ou face à face si vous êtes sur Paris)","CV remanié"], price: 99.00, entry_service: false, hrsunit: true, hrsbundle: false, options: "CV en anglais : +49€ / CV bilingue (FR + EN): +99€")
update_linkedin = Hrservice.create!(title: "Update LinkedIn", description: "Votre profil LinkedIn aux petits oignons et votre stratégie digitale bien organisée", conditions: ["Entretien initial de 45 min pour cibler votre besoin","Analyse de votre CV par un RH","Analyse de votre présence internet par un expert communication digitale","Entretien de restitution 45min (Skype ou face à face si vous êtes sur Paris)","Synthèse des recommandations et profil à jour"], price: 149.00, entry_service: false, hrsunit: true, hrsbundle: false, options: "profil en anglais : +99€ / CV bilingue (FR + EN): +149€")
update_lm = Hrservice.create!(title: "Update lettre de motivation", description: "Une lettre de motivation sans bullshit, personnelle et efficace", conditions: ["Entretien initial de 45 min pour comprendre votre parcours et cibler votre besoin","Analyse de votre lettre de motivation actuelle (si elle existe…)","Regard complémentaire d’un expert en communication","Entretien de restitution 45min (Skype ou face à face si vous êtes sur Paris)","Lettre de motivation rédigée"], price: 149.00, entry_service: false, hrsunit: true, hrsbundle: false, options: "lettre en anglais : +99€ / lettre bilingue (FR + EN): +149€")
preparation_entretien = Hrservice.create!(title: "Préparation entretien", description: "La meilleure façon de réussir ses entretiens, c’est de pouvoir faire comme si vous y étiez… avant de vous retrouver face au recruteur", conditions: ["Entretien d’1h30 comportant 45min d’entretien / 45 min de débriefing  (Skype ou face à face si vous êtes sur Paris)","Recommandations renvoyées à l’issue de l’entretien"], price: 99.00, entry_service: false, hrsunit: true, hrsbundle: false, options: "entretien en anglais +49€")
ask_donnie = Hrservice.create!(title: "Ask Donnie!", description: "Donnie! vous apporte un éclairage RH sur une questions précise que vous vous posez, et vous aide à prendre du recul par rapport à une situation", conditions: ["Analyse et diagnostic RH de vos questions","Débriefing oral (Skype) ou écrit, selon le besoin"], price: 80.00, entry_service: false, ondemand_service: true, hrsunit: true, hrsbundle: false, options: "un devis précis vous sera envoyé pour valider la prestation")
bilan_donnie_egaree = Hrservice.create!(title: "Je me sens comme une brebis égarée", subtitle: "Mon job actuel ne me fait plus vibrer, je sais ce qui ne va pas mais je ne sais pas ce que je veux", description: "Donnie! vous aide à faire un point sur votre situation actuelle pour vous permettre de prendre les bonnes décisions pour la suite / pour retrouver votre kiff", conditions: ["Entretien initial - 1h - pour comprendre votre situation","Analyse de votre parcours","Approfondissement de votre profil (Test type MBTI - aptitudes professionnelles)","Entretien de débriefing - 1h - présentation des conclusions et recommandations"], price: 199.00, entry_service: false, hrsunit: false, hrsbundle: true, options: "en anglais +99€")
tranhumance = Hrservice.create!(title: "Je prépare ma tranhumance", subtitle: "Ma décision est prise, je change de job (dans mon entreprise/dans une autre entreprise)… mais je ne sais pas comment m’y prendre pour être sûr(e) que ça marche", description: "Donnie! vous accompagne dans toutes les étapes de votre candidature, du CV à l’entretien d’embauche… Votre personal trainer, mais pour votre carrière", conditions: ["Entretien initial - 1h - pour comprendre votre situation","Analyse de votre parcours et de votre CV (RH)","Analyse de votre empreinte digitale (expert communication digitale)","Entretien de débriefing - 1h - et finalisation de votre CV/LinkedIn en fonction de vos remarques","2 entretiens de préparation"], price: 499.00, entry_service: false, hrsunit: false, hrsbundle: true, options: "en anglais +99€ / bilingue: +149€")
changer_bergerie = Hrservice.create!(title: "Je veux changer de bergerie", subtitle: "J’ai identifié mon prochain poste - ailleurs, d’ailleurs j’ai presque signé, mais je ne sais pas comment gérer mon départ de CDI… ", description: "Donnie! analyse avec vous votre situation actuelle pour trouver la meilleure option de sortie", conditions: ["Entretien initial - 45 min","Analyse de votre situation actuelle","Sollicitations d’expertise (si besoin)","Entretien débriefing - 1h - et présentation des recommandations","Synthèse écrite"], price: 249.00, entry_service: false, hrsunit: false, hrsbundle: true)
loup = Hrservice.create!(title: "Je crois qu'il y a un loup dans ma bergerie, j'ai besoin d'aide", subtitle: "Mon job actuel ne me fait plus vibrer, je sais ce qui ne va pas mais je ne sais pas ce que je veux", description: "Vous avez rencontré un loup ces dernières semaines dans le cadre de votre activité professionnelle, et vous ne savez pas vers qui vous tourner pour avec un avis circonstancié ? Donnie! vous écoute, sollicite son réseau d’experts pour vous et vous aide à trouver une solution. ", conditions: ["Entretien initial - 1h - pour comprendre votre situation","Sollicitation d’experts (si besoin)"], price: 99.00, entry_service: false, hrsunit: false, hrsbundle: true, options: "Un devis sera établi pour vous donner une vision précise au lancement de la prestation")

puts "Seed OK"
